### ISSUE TITLE
Production build fail with UglifyJs

### ISSUE THREAD

**Issue by kylewelsby** [ceri-comps/ceri-icon#2]
When building ceri-icon for production, UglifyJs complains and fails the build with the following error message.

```
ERROR in static/js/vendor.af3c5ebf60c12e8af0a3.js from UglifyJs
Unexpected token: name (Ceri) [./~/ceri/lib/wrapper.js:15,0][static/js/vendor.af3c5ebf60c12e8af0a3.js:76957,16]
```

code

```JavaScript
// src/helpers/ceri-icon.js
import icon from 'ceri-icon'
require('document-register-element')
window.customElements.define('app-icon', icon)
```

```JavaScript
// src/main.js

// ... Many other dependancies
import './helpers/ceri-icon'

```

**Comment by paulpflug** [comment]
Just quick: cerijs tries to use es6 for custom elements. Thus uglify needs 
es6 support:
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/README.md


Am 21. April 2017 11:51:55 schrieb Kyle Welsby <notifications@github.com>:

**Comment by ShonM** [comment]
https://github.com/babel/babili works great for this

**Comment by nikolay-borzov** [comment]
I tried this. It works, but throws an exception for each icon element

```
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: [
    helpers.resolvePath('src'),
    path.join(__dirname, '../node_modules/ceri')
  ]
},
```

**Comment by kylewelsby** [comment]
stale project closing issue
